export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const START_GET_TASK = 'START_GET_TASK';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_ERROR = 'GET_TASK_ERROR';

export const GET_TASK_DELETED = 'GET_TASK_DELETED';
export const TASK_DELETED_SUCCESS = 'TASK_DELETED_SUCCESS';
export const TASK_DELETED_ERROR = 'TASK_DELETED_ERROR';

export const GET_TASK_EDITED = 'GET_TASK_EDITED';
export const TASK_EDITED_SUCCESS = 'TASK_EDITED_SUCCESS';
export const TASK_EDITED_ERROR = 'TASK_EDITED_ERROR';

export const START_TASK_EDITED = 'START_TASK_EDITED';